### ISSUE TITLE
No content is shown

### ISSUE THREAD

**Issue by obiwanjacobi** [camalot/plugin.video.microsoft.channel9#16]
On Kodi 17. Installed fine and runs fine but does not show any content.
Cannot see any errors in the debug log, either...

**Comment by obiwanjacobi** [comment]
Did find an error at last but I think it is an isolated problem.
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'findAll'
                                            Traceback (most recent call last):
                                              File "C:\Users\marc\AppData\Roaming\Kodi\addons\plugin.video.microsoft.channel9\addon.py", line 87, in <module>
                                                plugin.Main()
                                              File "C:\Users\marc\AppData\Roaming\Kodi\addons\plugin.video.microsoft.channel9\resources\lib\series.py", line 35, in __init__
                                                self.browse()
                                              File "C:\Users\marc\AppData\Roaming\Kodi\addons\plugin.video.microsoft.channel9\resources\lib\series.py", line 92, in browse
                                                li_entries = ul_entries.findAll("li")
                                            AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by obiwanjacobi** [comment]
And this:
ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.microsoft.channel9/?action=list-all&page=1&sort=Most%20Viewed
21:44:28.394 T:6072   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.microsoft.channel9/?action=list-all&page=1&sort=Most%20Viewed) failed
21:44:28.394 T:6072   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.microsoft.channel9/?action=list-all)
21:44:28.394 T:6072   DEBUG:   ParentPath = [plugin://plugin.video.microsoft.channel9/]

Hope it helps

**Comment by camalot** [comment]
Make sure you have the latest version. there was an issue with it displaying because they changed the content on channel9 on how the videos are displayed. this was corrected. From your error, it looks like you have an older version. install version 2.0.63.28717 and see if the problem persists. 

There is a problem that I haven't fixed yet with the repository and being able to push updates from the repo.

**Comment by obiwanjacobi** [comment]
The 50 zip was in the 63 zip that was my mistake - didn't look at the numbers.
I zipped the plaind folder that is in the 63 zip and installed from that - and it works fine now.

Thanx for the pointer.
